In [8]:
import sys
import os

sys.path.append(os.getcwd())

import mydict.wingman as wm
import mydict.main_sa as sa
import mydict.algorithm as alg
import mydict.gen_data as gd

In [2]:
import numpy as np

In [3]:
label_element = [0, 1, 2]
each_subgroup_size = 150
N = len(label_element) * each_subgroup_size
machine_num = 3  #3/6/9
each_machine_size = N // machine_num

gen_way = 'normal_uniform_mixed'
is_hete_intercept = True
qq = 3
pp = 3

ori_seed = 42

In [4]:
local_real_Y, local_real_X, local_real_Z, local_real_label, real_beta, local_real_Theta, final_data = gd.gen_distributed_data(
    label_element=label_element,
    n=each_subgroup_size,
    qq=qq,
    pp=pp,
    is_hete_intercept=is_hete_intercept,
    machine_num=machine_num,
    gen_way=gen_way,
    seed=ori_seed)

In [5]:
lam_list_st1 = np.around(np.linspace(1, 2, 5), 3)
print(lam_list_st1)
lam_list_st2 = np.around(np.linspace(3, 4, 5), 3)
print(lam_list_st2)

[1.   1.25 1.5  1.75 2.  ]
[3.   3.25 3.5  3.75 4.  ]


In [6]:
real_Y = final_data['oriY_shuffle']
real_X = final_data['real_X_shuffle']
real_Z = final_data['real_Z_shuffle']
real_beta = final_data['real_beta']
real_Theta = final_data['real_Theta_shuffle']
real_label = final_data['real_label_shuffle']
distributed_index = np.array_split(np.arange(len(real_Y)), machine_num)

obj_dsfpr = alg.DSFPR(
    machine_num=machine_num,
    sample_index=distributed_index,
    oriZ=real_Z,
    oriY=real_Y,
    oriX=real_X,
    lam_list_st1=lam_list_st1,
    lam_list_st2=lam_list_st2,
    real_label=real_label,
    real_beta=real_beta,
    real_theta=real_Theta,
    vertheta=3,
    gamma=1,
    doorsill_st1=0.01,
    doorsill_st2=0.5,
    tolerance=0.001,
    T0=500,
    T1=1000,
    c1=1,
    get_res=0, 
    iniway='kmeans',  
    inik=None,
    hot_start=False,
    intercept_hete=True,
    parallel_stage1=True,
    parallel_stage2=True,
)

obj_dsfpr.fit()


iniway is kmeans
inik is: 6
ini_kforeachgroup: [47. 25. 16. 21. 15. 26.]
iniway is kmeans
inik is: 6
ini_kforeachgroup: [12. 25. 58. 14. 20. 21.]
iniway is kmeans
inik is: 6
ini_kforeachgroup: [27. 47. 16. 22. 25. 13.]
pre_stage1 is not executed, executing pre_stage1 first
pre_stage2 is executed, please check the results
Model:        Stage1 finished, 3 local machines	
Size:        (N,q,p)=((450, 4, 3))
Real.K&Est.K:  (3,10)
Est.EachNum:  ([51 52 47 25 58 46 21 51 47 52])
RI_st1 & sub_RI & quasi_RI:            (0.7690967582281614, 0.7778371690175699, 0.988210838901262)
FDR_st1:            0.01723158492709714
ARI_st1:            0.37085038210042093
RMSE_beta_st1:    0.021583973492733118
Sub_oracle_RMSE_beta: 0.015752276348500918
Quasi_oracle_RMSE_beta: 0.020434624474201794
Oracle_RMSE_beta: 0.015660700532018148
RMSE_theta_st1:   0.4185106990402384
Sub_oracle_RMSE_theta_st1: 0.16156162595227963
Quasi_oracle_RMSE_theta_st1: 0.2101639862880168
Oracle_RMSE_theta_st1: 0.06292091171803404
RMS

In [7]:
print(obj_dsfpr.master_machine.fiZeta)

[[1.07443789 0.93403093 0.863037   1.12129499]
 [4.8759669  5.01160125 5.11442196 5.00181777]
 [2.90334145 3.09994322 2.99029229 3.10525324]]
